import { GuardianFix, GuardianViewMode } from "../../hooks/useGuardian";
import { GuardianVesselScope } from "../../hooks/types";
import { IVessel } from "@webstack/components/ThreeComponents/UiMap/models/IMapVessel";
import React from "react";

export type GuardianLookupNote = {
  tone: "info" | "error";
  message: string;
};

export type GuardianPanelProps = {
  tracking: boolean;
  statusLabel: string;
  lastFix?: GuardianFix;
  lastBackendSync?: number;
  error?: string;
  permissionDenied?: boolean;
  shareUrl: string;
  deviceInfo?: any;
  deviceId?: string;
  deviceLabel?: string;
  deviceType?: string;
  devices?: GuardianFix[];
  visibleVessels?: IVessel[];
  clearanceLevel?: number;
  userName?: string | null;
  userId?: string | null;
  isAuthenticated: boolean;
  viewUserId: string;
  viewDeviceId?: string;
  viewFriendName?: string;
  friends: string[];
  friendsLoading?: boolean;
  friendDisplayNames?: Record<string, string>;
  adminVessels?: IVessel[];
  adminPage?: number;
  adminPageSize?: number;
  adminTotal?: number;
  onAdminPageChange?: (page: number) => void;
  onAdminPageSizeChange?: (size: number) => void;
  viewMode: GuardianViewMode;
  onViewUserIdChange: (val: string) => void;
  onLookupUser: (id?: string) => void;
  onAddFriend: (id?: string) => void;
  onSelectFriend: (id: string) => void;
  onRemoveFriend: (id: string) => void;
  shareDeviceId?: string | null;
  onShareDeviceChange?: (id: string) => void;
  onToggleTracking: () => void;
  canRecenter?: boolean;
  onRecenter: () => void;
  onViewModeChange: (mode: GuardianViewMode) => void;
  timeline: GuardianFix[];
  timelineLoading: boolean;
  onRefreshTimeline: () => void;
  uploadIntervalSec: number;
  onUploadIntervalChange: (sec: number) => void;
  staleFix?: boolean;
  lookupNote?: GuardianLookupNote | null;
  vesselScope?: GuardianVesselScope;
  onVesselScopeChange?: (scope: GuardianVesselScope) => void;
  vesselSearch?: string;
  onVesselSearchChange?: (value: string) => void;
  deviceTypeFilter?: string;
  onDeviceTypeFilterChange?: (value: string) => void;
  deviceTypeOptions?: string[];
  visibleTableVessels?: IVessel[];
  trackingVessels?: IVessel[];
  trackingGridVessels?: IVessel[];
  onRemoveVessel?: (vesselId: string) => void | Promise<void>;
  onPurgeAllTracking?: () => void | Promise<void>;
  mapOrientation?: "north" | "heading";
  onMapOrientationChange?: (value: "north" | "heading") => void;
  headingAvailable?: boolean;
  trackingResumePending?: boolean;
  panelCollapsed?: boolean;
  onResizeHandlePointerDown?: (event: React.PointerEvent) => void;
  onPanelHandleClick?: () => void;
  desktopMode?: boolean;
  panelWidth?: number;
};

export type Props = GuardianPanelProps;
